name : My first workflow

on:
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name : Welcome
        run : echo "Hi, welcome to GitHub Actions"
      - name : Bye
        run : echo "Good bye to the actions"
