name : My first workflow

on:
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name : Welcome
        run : echo "Hi, welcome to GitHub Actions"
      - name : checking out code
        uses: actions/checkout@v4
        with:
          python-version: "3.12"
      - name: Listing out python version
        run : python --version
      - name : Listing out pip version
        run : pip --version
      - name: List files
        run : ls -la
      - name : Bye
        run : echo "Good bye to the actions"
